### PR TITLE
Chat interface hosting web components

### PR DESCRIPTION
**Pull request by EvelynBunnyDev**
Successfully loaded a web placeholder (google) in chat interface

# *Swift Chat Interface*

## :recycle: Current situation & Problem
*New branch that hosts an interactive React web view within the SwiftUI interface*

## :gear: Release Notes 
*Added WebView under Chat as a SwiftUI Wrapper*
*Modified ChatView under Chat to host desired website. Currently I put localhost for Prisma web as a placeholder, which works.*
`if let url = URL(string: "https://www.google.com/")` 
*Need additional work on formatting.*
1. Chat interface should not zoom in after typing initial message.
2. Ensuring consistency across iPads and iPhones.
3. Next step is implementing user authentication.

## :books: Documentation
*Please reference in-line documentation.* 
image

## :white_check_mark: Testing
*All tests passed.*
*Additional tests to be added for web performance.*

## :pencil: Code of Conduct & Contributing Guidelines 

By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md):
- [x] I agree to follow the [Code of Conduct](https://github.com/CS342/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/CS342/.github/blob/main/CONTRIBUTING.md).

### CODE REVIEW

**Comment by mjoerke** [comment]
Hi @EvelynBunnyDev, thank you for the PR! This is exciting. 

If you replace the url with `if let url = URL(string: "http://localhost:3000")` while locally running the frontend, you should be able to see our chat interface from the app in the simulator.

**Comment by EvelynBunnyDev** [comment]
Hi @mjoerke (This is Evelyn Song @EvelynBunnyDev, not Evelyn Hur :)) I have replaced the link with localhost and the chat interface was successfully loaded! I am currently troubleshooting formatting errors. I believe this would make a great demo on the midterm presentation.

**Comment by mjoerke** [comment]
Great! Sorry for mixing up your usernames 🙃

**Comment by PSchmiedmayer** [comment]
@EvelynBunnyDev Great to see the progress! Feel free to request reviews from your team members, if you have any specific question for me just tag me in a comment 🚀

**Review by dhruvna1k — APPROVED** [review]

**Pull request merged**
